[0m22:25:32.974045 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9680f3e560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9680103b20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9680103ac0>]}


============================== 22:25:32.980593 | 2c85f9c9-e8a1-4c9c-b9ca-d61d7ba7c698 ==============================
[0m22:25:32.980593 [info ] [MainThread]: Running with dbt=1.9.4
[0m22:25:32.982418 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/huseyn/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt init', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m22:25:33.006976 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object.. Dictionary: {'dir': PosixPath('/home/huseyn/.dbt')}
[0m22:25:33.008430 [info ] [MainThread]: Creating dbt configuration folder at 
[0m22:25:52.903073 [debug] [MainThread]: Starter project path: /home/huseyn/.local/lib/python3.10/site-packages/dbt/include/starter_project
[0m22:25:53.121010 [info ] [MainThread]: 
Your new dbt project "data_flow" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m22:25:53.123420 [info ] [MainThread]: Setting up your profile.
[0m22:35:33.884292 [info ] [MainThread]: Profile data_flow written to /home/huseyn/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m22:35:33.898425 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 601.0132, "process_in_blocks": "78640", "process_kernel_time": 0.258693, "process_mem_max_rss": "112576", "process_out_blocks": "8", "process_user_time": 2.097264}
[0m22:35:33.906116 [debug] [MainThread]: Command `dbt init` succeeded at 22:35:33.905501 after 601.02 seconds
[0m22:35:33.920256 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9680f3e560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9680116740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9680103a00>]}
[0m22:35:33.923121 [debug] [MainThread]: Flushing usage events
[0m22:35:34.571766 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:01:59.478820 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3bf07d6560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3bef9fc4c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3bef9fc550>]}


============================== 23:01:59.484397 | 753baf43-855c-4342-979f-8f23202644a8 ==============================
[0m23:01:59.484397 [info ] [MainThread]: Running with dbt=1.9.4
[0m23:01:59.486482 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/huseyn/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt deps', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m23:01:59.488625 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /mnt/c/Users/ping/Documents/Bootcamps/Data-Analytics-Engineer-Bootcamp/dataflow/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:01:59.491756 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.1134615, "process_in_blocks": "59200", "process_kernel_time": 0.138012, "process_mem_max_rss": "89968", "process_out_blocks": "8", "process_user_time": 1.853313}
[0m23:01:59.493587 [debug] [MainThread]: Command `dbt deps` failed at 23:01:59.493332 after 0.12 seconds
[0m23:01:59.495277 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3bf07d6560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3bef9fcb50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3bef9fc280>]}
[0m23:01:59.498156 [debug] [MainThread]: Flushing usage events
[0m23:02:00.071371 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:02:16.619570 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f13acaaa5c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f13abccc5e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f13abccc640>]}


============================== 23:02:16.623710 | 741a82e6-b8aa-482b-ac92-32f34ed0b5c4 ==============================
[0m23:02:16.623710 [info ] [MainThread]: Running with dbt=1.9.4
[0m23:02:16.625547 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/home/huseyn/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt deps', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m23:02:16.627849 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /mnt/c/Users/ping/Documents/Bootcamps/Data-Analytics-Engineer-Bootcamp/dataflow/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:02:16.630207 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.09543005, "process_in_blocks": "0", "process_kernel_time": 0.060127, "process_mem_max_rss": "90036", "process_out_blocks": "0", "process_user_time": 1.683556}
[0m23:02:16.632094 [debug] [MainThread]: Command `dbt deps` failed at 23:02:16.631874 after 0.10 seconds
[0m23:02:16.634368 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f13acaaa5c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f13abccc9d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f13abccc3a0>]}
[0m23:02:16.636588 [debug] [MainThread]: Flushing usage events
[0m23:02:17.158083 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:59:49.740632 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5d24106560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5d23328430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5d23328490>]}


============================== 13:59:49.747259 | d0f814f5-d2a9-4f7f-92ac-c956f488bffe ==============================
[0m13:59:49.747259 [info ] [MainThread]: Running with dbt=1.9.4
[0m13:59:49.749389 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/huseyn/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:59:49.751239 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /mnt/c/Users/ping/Documents/Bootcamps/Data-Analytics-Engineer-Bootcamp/dataflow/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:59:49.754144 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.09512838, "process_in_blocks": "47128", "process_kernel_time": 0.189549, "process_mem_max_rss": "90212", "process_out_blocks": "0", "process_user_time": 1.695972}
[0m13:59:49.756214 [debug] [MainThread]: Command `dbt run` failed at 13:59:49.756012 after 0.10 seconds
[0m13:59:49.757454 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5d24106560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5d23328b20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5d23328430>]}
[0m13:59:49.758710 [debug] [MainThread]: Flushing usage events
[0m13:59:50.342273 [debug] [MainThread]: An error was encountered while trying to flush usage events
